// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYyieXH45wQ-g0xckH4i3cguLOfMaR24',
    appId: '1:652774147411:web:8d4289c28c238ed6f60da6',
    messagingSenderId: '652774147411',
    projectId: 'bdelete-5657a',
    authDomain: 'bdelete-5657a.firebaseapp.com',
    storageBucket: 'bdelete-5657a.appspot.com',
    measurementId: 'G-FD1C7CVVGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvgsb0SMpGFqePcWzqOS7R3487V5eGe0',
    appId: '1:652774147411:android:e06e0ef8fa6ed865f60da6',
    messagingSenderId: '652774147411',
    projectId: 'bdelete-5657a',
    storageBucket: 'bdelete-5657a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSW79UP9LLRA6--T2UUhhkook6LgL84wk',
    appId: '1:652774147411:ios:ce6ed2dc98a953d3f60da6',
    messagingSenderId: '652774147411',
    projectId: 'bdelete-5657a',
    storageBucket: 'bdelete-5657a.appspot.com',
    iosBundleId: 'com.example.bdelete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSW79UP9LLRA6--T2UUhhkook6LgL84wk',
    appId: '1:652774147411:ios:ce6ed2dc98a953d3f60da6',
    messagingSenderId: '652774147411',
    projectId: 'bdelete-5657a',
    storageBucket: 'bdelete-5657a.appspot.com',
    iosBundleId: 'com.example.bdelete',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATYyieXH45wQ-g0xckH4i3cguLOfMaR24',
    appId: '1:652774147411:web:090cecd98c9ab460f60da6',
    messagingSenderId: '652774147411',
    projectId: 'bdelete-5657a',
    authDomain: 'bdelete-5657a.firebaseapp.com',
    storageBucket: 'bdelete-5657a.appspot.com',
    measurementId: 'G-EWJRW4TRVQ',
  );
}
